---
sudo: required

services:
  - docker

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ devel universe" | sudo tee /etc/apt/sources.list.d/devel-universe.list
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends qemu-user-static binfmt-support

script:
  - docker build -t ansible-role-deluge tests/support
  - docker run -it -v $PWD:/role ansible-role-deluge
  - docker run -it -v $PWD:/role --env EXTRA_VARS='deluge_web=False' ansible-role-deluge

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
